#!/bin/sh
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication postProcess -dict system/postProcessDict

#------------------------------------------------------------------------------
